### ISSUE TITLE
  Cannot find module './apl/undefined/document.json'

### ISSUE THREAD

**Issue by mandar-raj** [jovotech/jovo-templates#53]
hi
i just launch invocation getting below error

apl/undefined/document.json

Error -----------------------------------------------------------------

  Code:
  MODULE_NOT_FOUND

  Message:
  Cannot find module './apl/undefined/document.json'
  Require stack:
  - C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\src\app.js
  - C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\src\index.js

  Stack:
  Error: Cannot find module './apl/undefined/document.json'
  Require stack:
  - C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\src\app.js
  - C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\src\index.js
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
      at Function.Module._load (internal/modules/cjs/loader.js:842:27)
      at Module.require (internal/modules/cjs/loader.js:1026:19)
      at require (internal/modules/cjs/helpers.js:72:18)
      at AlexaSkill.ShowTemplateIntent (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\src\app.js:39:22)
      at Function.applyHandle (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\node_modules\jovo-core\src\plugins\Handler.ts:177:35)
      at handle (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\node_modules\jovo-core\src\plugins\Handler.ts:239:19)
      at Middleware.run (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\node_modules\jovo-core\src\core\Middleware.ts:85:11)
      at App.handle (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\node_modules\jovo-core\src\core\BaseApp.ts:274:7)
      at App.handle (C:\Users\hp 1\AppData\Roaming\npm\alexa-apl\node_modules\jovo-framework\src\App.ts:333:5)

   ----------------------------------------------------------------------

**Comment by jankoenig** [comment]
This is the part in the `app.js` where it's throwing the error:

```
const document = require(`./apl/${template.id}/document.json`);
```

The error message states it can't find `apl/undefined/document.json`, so it seems like the `template` input isn't set.

How are you testing it?
